
const repos = [
  {id: 1,
  name:"Horizontal stable monitoring",
  description:"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.",
  tags:"Upgradable",
  stars:39,
  forks:62,
  updated:39,
  script:null},
  {id:2,
    name:"Up-sized user-facing solution",
    description:"Nulla ut erat id mauris vulputate elementum.",tags:"Optimized",
    stars:4,
    forks:15,
    updated:34,
    script:null},
  {id:3,
    name:"Compatible fresh-thinking array",description:"Pellentesque eget nunc.",
    tags:"orchestration",
    stars:82,
    forks:43,
    updated:25,
    script:null},
  {id:4,
    name:"Stand-alone encompassing groupware",
    description:"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.",tags:"throughput",stars:37,forks:22,updated:13,script:null},
  {id:5,name:"Balanced clear-thinking framework",description:"Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",tags:"interface",stars:97,forks:64,updated:30,script:null},
  {id:6,name:"Virtual object-oriented array",description:"In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",tags:"Managed",stars:40,forks:38,updated:43,script:null},
  {id:7,name:"Intuitive multi-tasking definition",description:"Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",tags:"Phased",stars:4,forks:23,updated:24,script:null},
  {id:8,name:"Triple-buffered cohesive interface",description:"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.",tags:"monitoring",stars:68,forks:68,updated:8,script:null},
  {id:9,name:"User-friendly composite productivity",description:"Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",tags:"Managed",stars:41,forks:14,updated:9,script:null},
  {id:10,name:"Compatible next generation solution",description:"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",tags:"budgetary management",stars:73,forks:36,updated:3,script:null},
  {id:11,name:"Vision-oriented coherent utilisation",description:"Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.",tags:"Stand-alone",stars:63,forks:92,updated:24,script:null},
  {id:12,name:"Re-engineered responsive middleware",description:"Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.",tags:"collaboration",stars:73,forks:68,updated:44,script:null},
  {id:13,name:"Enhanced analyzing interface",description:"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue",tags:"Team-oriented",stars:13,forks:23,updated:20,script:null},
  {id:14,name:"Multi-lateral empowering encoding",description:"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. ",tags:"client-server",stars:44,forks:70,updated:21,script:null},
  {id:15,name:"Synergized contextually-based collaboration",description:"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",tags:"needs-based",stars:30,forks:11,updated:3,script:null},
  {id:16,name:"Optimized next generation process improvement",description:"In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.",tags:"multi-tasking",stars:54,forks:8,updated:2,script:null},
  {id:17,name:"Inverse multi-tasking definition",description:"Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",tags:"Networked",stars:54,forks:70,updated:30,script:null},
  {id:18,name:"Distributed clear-thinking open architecture",description:"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",tags:"demand-driven",stars:37,forks:99,updated:34,script:null},
  {id:19,name:"Assimilated bifurcated emulation",description:"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",tags:"Enhanced",stars:48,forks:25,updated:12,script:null},
  {id:20,name:"Focused even-keeled interface",description:"Donec dapibus. Duis at velit eu est congue elementum.",tags:"Synergized",stars:3,forks:90,updated:46,script:null}]
