
export const repos = [
  {id: 1,
  name:"Horizontal stable monitoring",
  description:"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.",
  tags:"Upgradable",
  stars:39,
  forks:62,
  updated:39,
  isPinned:true,
  script:"javascript"},
  {id:2,
    name:"Up-sized user-facing solution",
    description:"Nulla ut erat id mauris vulputate elementum.",tags:"Optimized",
    stars:4,
    forks:15,
    updated:34,
    isPinned:true,
    script:"typescript"},
  {id:3,
    name:"Compatible fresh-thinking",description:"Pellentesque eget nunc.",
    tags:"orchestration",
    stars:82,
    forks:43,
    updated:25,
    isPinned:false,
    script:"typescript"},
  {id:4,
    name:"Stand-alone encompassing groupware",
    description:"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.",
    tags:"throughput",
    stars:37,
    forks:22,
    updated:13,
    isPinned:false,
    script:"typescript"},
  {id:5,
    name:"Balanced clear-thinking framework",
    description:"Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    tags:"interface",
    stars:97,
    forks:64,
    updated:30,
    isPinned:false,
    script:"typescript"},
  {id:6,
    name:"Virtual object-oriented",
    description:"In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",tags:"Managed",
    stars:40,
    forks:38,
    updated:43,
    isPinned:false,
    script:"typescript"}
  ]
